const $=id=>document.getElementById(id),B=n=>(n&15).toString(2).padStart(4,'0');
const ops=['ADD','SUB','MUL','DIV','MOD','INC','DEC','SHL','SHR','AND','OR','XOR','NOT','EQ','GT','LT','MAX','MIN','CARRY','BORROW','POPC','DICE','ROUND'];
const base=['두 수 더하기|ADD|3|5','두 수 빼기|SUB|9|4','두 수 곱하기|MUL|3|4','몫 구하기|DIV|13|3','나머지 구하기|MOD|13|3','1 증가|INC|7|1','1 감소|DEC|7|1','왼쪽 shift|SHL|6|1','오른쪽 shift|SHR|9|1','AND 마스크|AND|13|3','OR set-bit|OR|8|2','XOR 차이 검출|XOR|10|12','NOT 반전|NOT|10|0','동등 비교|EQ|7|7','A>B 비교|GT|9|4','A<B 비교|LT|4|9','최댓값 선택|MAX|4|9','최솟값 선택|MIN|4|9','carry flag|CARRY|9|8','borrow flag|BORROW|4|9','popcount|POPC|11|0','주사위 매핑|DICE|9|0','정수 반올림|ROUND|13|4'];
const tasks=base.map((s,i)=>{let[a,b,c,d]=s.split('|');return{title:a,op:b,a:+c,b:+d}});while(tasks.length<100){let i=tasks.length,op=ops[i%ops.length];tasks.push({title:`datapath exercise ${i+1}: ${op}`,op,a:(i*3)%16,b:(i*5+1)%16})}
const ins={0:'NOP',1:'LDA',2:'LDB',3:'ADD',4:'SUB',5:'AND',6:'OR',7:'OUT',8:'MUL',9:'DIV',10:'CALC',15:'HLT'};
let mem=Array(16).fill(0),cpu={pc:0,ir:0,a:0,b:0,acc:0,out:0,input:3,phase:0,halt:false,run:false},task=null;
function opcode(op){return{ADD:3,SUB:4,AND:5,OR:6,MUL:8,DIV:9}[op]||10}
function calc(op,a,b){a&=15;b&=15;let r=0,n='';switch(op){case'ADD':r=a+b;break;case'SUB':r=a-b;break;case'MUL':r=a*b;break;case'DIV':r=b?Math.floor(a/b):0;n=b?`remainder ${a%b}`:'divide by zero';break;case'MOD':r=b?a%b:0;break;case'INC':r=a+1;break;case'DEC':r=a-1;break;case'SHL':r=a<<1;break;case'SHR':r=a>>1;break;case'AND':r=a&b;break;case'OR':r=a|b;break;case'XOR':r=a^b;break;case'NOT':r=(~a)&15;break;case'EQ':r=a===b?1:0;break;case'GT':r=a>b?1:0;break;case'LT':r=a<b?1:0;break;case'MAX':r=Math.max(a,b);break;case'MIN':r=Math.min(a,b);break;case'CARRY':r=a+b>15?1:0;break;case'BORROW':r=a<b?1:0;break;case'POPC':r=B(a).split('').filter(x=>x==='1').length;break;case'DICE':r=a%6+1;break;case'ROUND':{let u=Math.max(1,b);r=Math.floor((a+Math.floor(u/2))/u)*u;break}default:r=a+b}if(!n&&(r>15||r<0))n='4-bit truncation';return{raw:r,val:r&15,n}}
function current(){return tasks[+$('task').value||0]}function prog(t){let o=opcode(t.op);return[[0,1,'LDA','IN→A'],[1,2,'LDB','IN→B'],[2,o,ins[o],o===10?'selected op→ACC':`${ins[o]}→ACC`],[3,7,'OUT','ACC→OUT'],[4,15,'HLT','halt']]}
function setup(){tasks.forEach((t,i)=>$('task').add(new Option(`${String(i+1).padStart(3,'0')}. ${t.title}`,i)));$('task').value=0;$('ain').value=tasks[0].a;$('bin').value=tasks[0].b;renderTask()}
function renderTask(){let t=current(),a=+$('ain').value&15,b=+$('bin').value&15,r=calc(t.op,a,b);$('sum').innerHTML=`A=${a}(${B(a)}) · B=${b}(${B(b)}) · expected=${r.val}(${B(r.val)}) · actual=${task&&task.actual!=null?task.actual+'('+B(task.actual)+')':'not executed'}`;$('mem').innerHTML='<table><tr><th>addr</th><th>op</th><th>bits</th><th>effect</th></tr>'+prog(t).map(x=>`<tr><td>0x${x[0].toString(16)}</td><td>${x[2]}</td><td>${B(x[1])}</td><td>${x[3]}</td></tr>`).join('')+'</table>'}
function load(){let t=current(),a=+$('ain').value&15,b=+$('bin').value&15;if(['DIV','MOD'].includes(t.op)&&!b){b=1;$('bin').value=1}mem=Array(16).fill(0);prog(t).forEach(x=>mem[x[0]]=x[1]);task={...t,a,b,loaded:false,actual:null};cpu={pc:0,ir:0,a:0,b:0,acc:0,out:0,input:a,phase:0,halt:false,run:false};log(`load ${t.op}: A=${B(a)}, B=${B(b)}`);render()}
function regMode(n){let op=ins[cpu.ir];if(n==='A')return cpu.phase===2&&op==='LDA'?'LOAD':'HOLD';if(n==='B')return cpu.phase===2&&op==='LDB'?'LOAD':'HOLD';if(n==='ACC')return cpu.phase===3&&!['OUT','LDA','LDB','HLT'].includes(op)?'LOAD':'HOLD';if(n==='OUT')return cpu.phase===3&&op==='OUT'?'LOAD':'HOLD';return'HOLD'}
function reg(name,v,m){return`<div class=box><h3>${name} <span class='sig ${m==='LOAD'?'on':''}'>${m}</span></h3><div class=bits>${B(v).split('').map((b,i)=>`<div class='bit ${b==='1'?'one':''} ${m==='LOAD'?'load':''}'><small>Q${3-i}</small><b>${b}</b></div>`).join('')}</div></div>`}
function carry(a,b){let c=0,o=[];for(let i=0;i<4;i++){let s=((a>>i)&1)+((b>>i)&1)+c;o.unshift(`${c}→${s>1?1:0}`);c=s>1?1:0}return o}
function borrow(a,b){let c=0,o=[];for(let i=0;i<4;i++){let d=((a>>i)&1)-((b>>i)&1)-c;o.unshift(`${c}→${d<0?1:0}`);c=d<0?1:0}return o}
function aluPanel(){let op=ins[cpu.ir];if(op==='CALC')op=task?task.op:current().op;let r=calc(op,cpu.a,cpu.b),A=B(cpu.a).split(''),D=B(cpu.b).split(''),R=B(r.val).split(''),rows=[['bit','b3','b2','b1','b0'],['A',...A]];if(op!=='NOT')rows.push(['B',...D]);if(op==='ADD')rows.push(['carry',...carry(cpu.a,cpu.b)]);if(op==='SUB')rows.push(['borrow',...borrow(cpu.a,cpu.b)]);if(['AND','OR','XOR'].includes(op)){let s=op==='AND'?'∧':op==='OR'?'∨':'⊕';rows.push(['slice',...A.map((x,i)=>x+s+D[i])])}rows.push(['Y',...R]);$('aludetail').innerHTML=`<h3>ALU bit-slice: ${op}</h3><table>${rows.map(r=>'<tr>'+r.map(x=>`<td>${x}</td>`).join('')+'</tr>').join('')}</table><p>A=${B(cpu.a)} (${cpu.a}), B=${B(cpu.b)} (${cpu.b}), Y=${B(r.val)} (${r.val}). ${r.n}</p>`}
function render(){renderTask();['pc','ir','a','b','acc','out','input'].forEach(k=>$('r_'+k).textContent=B(cpu[k]));$('phase').textContent=['T0 Fetch','T1 Decode','T2 Execute','T3 Write-back'][cpu.phase];$('ir').textContent=`IR=${B(cpu.ir)} ${ins[cpu.ir]||'NOP'}`;$('pcbox').textContent=`PC=${B(cpu.pc)} selects RAM[${cpu.pc}] = ${ins[mem[cpu.pc]]||'NOP'} ${B(mem[cpu.pc]||0)}`;$('ctrl').textContent=`control=${['MEM_READ','LOAD_IR','ALU/LOAD','WRITE/INC'][cpu.phase]}`;$('regdetail').innerHTML=reg('Register A',cpu.a,regMode('A'))+reg('Register B',cpu.b,regMode('B'))+reg('Accumulator',cpu.acc,regMode('ACC'))+reg('Output latch',cpu.out,regMode('OUT'));aluPanel();$('leds').innerHTML=B(cpu.out).split('').map(x=>`<span class='led ${x==='1'?'on':''}'></span>`).join('')}
function log(s){let li=document.createElement('li');li.textContent=s;$('log').prepend(li);while($('log').children.length>12)$('log').lastChild.remove()}
async function step(){if(cpu.halt){log('halted');return}let op=ins[cpu.ir]||'NOP';if(cpu.phase===0){cpu.ir=mem[cpu.pc]||0;log(`fetch ${B(cpu.ir)} ${ins[cpu.ir]}`);cpu.phase=1}else if(cpu.phase===1){log(`decode ${ins[cpu.ir]}`);cpu.phase=2}else if(cpu.phase===2){op=ins[cpu.ir];if(op==='LDA'){cpu.a=cpu.input;log(`A <- ${B(cpu.input)}`)}else if(op==='LDB'){cpu.b=cpu.input;log(`B <- ${B(cpu.input)}`)}else if(['ADD','SUB','MUL','DIV','AND','OR'].includes(op)){cpu.acc=calc(op,cpu.a,cpu.b).val;log(`ALU ${op} -> ${B(cpu.acc)}`)}else if(op==='CALC'){cpu.acc=calc(task?task.op:current().op,cpu.a,cpu.b).val;log(`ALU ${task?task.op:current().op} -> ${B(cpu.acc)}`)}cpu.phase=3}else{op=ins[cpu.ir];if(op==='OUT'){cpu.out=cpu.acc;if(task)task.actual=cpu.out;log(`OUT <- ${B(cpu.out)}`)}if(op==='LDA'&&task&&!task.loaded){cpu.input=task.b;task.loaded=true;log(`input <- B ${B(cpu.input)}`)}if(op==='HLT'){cpu.halt=true;cpu.run=false;$('run').textContent='run';log('halt')}else cpu.pc=(cpu.pc+1)&15;cpu.phase=0}render()}
function loop(){if(!cpu.run)return;step().then(()=>setTimeout(loop,450))}function reset(){cpu={pc:0,ir:0,a:0,b:0,acc:0,out:0,input:task?task.a:cpu.input,phase:0,halt:false,run:false};if(task){task.actual=null;task.loaded=false}render();log('reset')}
setup();render();$('load').onclick=load;$('step').onclick=step;$('run').onclick=()=>{cpu.run=!cpu.run;$('run').textContent=cpu.run?'pause':'run';if(cpu.run)loop()};$('reset').onclick=reset;$('task').onchange=()=>{let t=current();$('ain').value=t.a;$('bin').value=t.b;renderTask()};$('ain').oninput=renderTask;$('bin').oninput=renderTask;log('ready');